export default [
  { id: 'GEN', name: 'Genesis' },
  { id: 'EXO', name: 'Exodus' },
  { id: 'LEV', name: 'Leviticus' },
  { id: 'NUM', name: 'Numeri' },
  { id: 'DEU', name: 'Deuteronomium' },
  { id: 'JOS', name: 'Jozua' },
  { id: 'JDG', name: 'Richteren' },
  { id: 'RUT', name: 'Ruth' },
  { id: '1SA', name: '1 Samuël' },
  { id: '2SA', name: '2 Samuël' },
  { id: '1KI', name: '1 Koningen' },
  { id: '2KI', name: '2 Koningen' },
  { id: '1CH', name: '1 Kronieken' },
  { id: '2CH', name: '2 Kronieken' },
  { id: 'EZR', name: 'Ezra' },
  { id: 'NEH', name: 'Nehemia' },
  { id: 'EST', name: 'Ester' },
  { id: 'JOB', name: 'Job' },
  { id: 'PSA', name: 'Psalmen' },
  { id: 'PRO', name: 'Spreuken' },
  { id: 'ECC', name: 'Prediker' },
  { id: 'SNG', name: 'Hooglied' },
  { id: 'ISA', name: 'Jesaja' },
  { id: 'JER', name: 'Jeremia' },
  { id: 'LAM', name: 'Klaagliederen' },
  { id: 'EZK', name: 'Ezechiël' },
  { id: 'DAN', name: 'Daniël' },
  { id: 'HOS', name: 'Hosea' },
  { id: 'JOL', name: 'Joël' },
  { id: 'AMO', name: 'Amos' },
  { id: 'OBA', name: 'Obadja' },
  { id: 'JON', name: 'Jona' },
  { id: 'MIC', name: 'Micha' },
  { id: 'NAM', name: 'Nahum' },
  { id: 'HAB', name: 'Habakuk' },
  { id: 'ZEP', name: 'Sefanja' },
  { id: 'HAG', name: 'Haggai' },
  { id: 'ZEC', name: 'Zacharia' },
  { id: 'MAL', name: 'Maleachi' },
  { id: 'MAT', name: 'Matteüs' },
  { id: 'MRK', name: 'Marcus' },
  { id: 'LUK', name: 'Lucas' },
  { id: 'JHN', name: 'Johannes' },
  { id: 'ACT', name: 'Handelingen' },
  { id: 'ROM', name: 'Romeinen' },
  { id: '1CO', name: '1 Korinthiërs' },
  { id: '2CO', name: '2 Korinthiërs' },
  { id: 'GAL', name: 'Galaten' },
  { id: 'EPH', name: 'Efeziërs' },
  { id: 'PHP', name: 'Filippenzen' },
  { id: 'COL', name: 'Kolossenzen' },
  { id: '1TH', name: '1 Tessalonicenzen' },
  { id: '2TH', name: '2 Tessalonicenzen' },
  { id: '1TI', name: '1 Timoteüs' },
  { id: '2TI', name: '2 Timoteüs' },
  { id: 'TIT', name: 'Titus' },
  { id: 'PHM', name: 'Filemon' },
  { id: 'HEB', name: 'Hebreeën' },
  { id: 'JAS', name: 'Jakobus' },
  { id: '1PE', name: '1 Petrus' },
  { id: '2PE', name: '2 Petrus' },
  { id: '1JN', name: '1 Johannes' },
  { id: '2JN', name: '2 Johannes' },
  { id: '3JN', name: '3 Johannes' },
  { id: 'JUD', name: 'Judas' },
  { id: 'REV', name: 'Openbaring' }
]
