name: Electron - Build and Release

on:
  push:
    branches:
      - dev
      - dev[0-9].*
  pull_request:
    branches:
      - dev[0-9].*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os:
          - windows-latest
      max-parallel: 1
      fail-fast: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x # use the latest LTS version of Node
      - name: Install dependencies
        run: npm ci
      - name: Build app
        if: github.ref != 'refs/heads/dev'
        run: npm run electron:build
      - name: Build & deploy app
        if: github.ref == 'refs/heads/dev'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run electron:release
