name: Build and Deploy dev environment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Install Functions Dependencies
        run: cd api && npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
